// JS/Data.js
const gameData = {
pastSimple: [
  { a: "be", b: "was/were", translation: "ser/estar" },
  { a: "beat", b: "beat", translation: "golpear" },
  { a: "become", b: "became", translation: "convertirse en" },
  { a: "begin", b: "began", translation: "empezar" },
  { a: "bend", b: "bent", translation: "doblar" },
  { a: "bet", b: "bet", translation: "apostar" },
  { a: "bite", b: "bit", translation: "morder" },
  { a: "blow", b: "blew", translation: "soplar" },
  { a: "break", b: "broke", translation: "romper" },
  { a: "bring", b: "brought", translation: "traer" },
  { a: "build", b: "built", translation: "construir" },
  { a: "burn", b: "burned/burnt", translation: "quemar" },
  { a: "buy", b: "bought", translation: "comprar" },
  { a: "catch", b: "caught", translation: "atrapar" },
  { a: "choose", b: "chose", translation: "elegir" },
  { a: "come", b: "came", translation: "venir" },
  { a: "cost", b: "cost", translation: "costar" },
  { a: "cut", b: "cut", translation: "cortar" },
  { a: "do", b: "did", translation: "hacer" },
  { a: "draw", b: "drew", translation: "dibujar" },
  { a: "dream", b: "dreamed/dreamt", translation: "soñar" },
  { a: "drink", b: "drank", translation: "beber" },
  { a: "drive", b: "drove", translation: "conducir" },
  { a: "eat", b: "ate", translation: "comer" },
  { a: "fall", b: "fell", translation: "caer" },
  { a: "feed", b: "fed", translation: "alimentar" },
  { a: "feel", b: "felt", translation: "sentir" },
  { a: "fight", b: "fought", translation: "pelear" },
  { a: "find", b: "found", translation: "encontrar" },
  { a: "fly", b: "flew", translation: "volar" },
  { a: "forget", b: "forgot", translation: "olvidar" },
  { a: "forgive", b: "forgave", translation: "perdonar" },
  { a: "freeze", b: "froze", translation: "congelar" },
  { a: "get", b: "got", translation: "obtener" },
  { a: "give", b: "gave", translation: "dar" },
  { a: "go", b: "went", translation: "ir" },
  { a: "grow", b: "grew", translation: "crecer" },
  { a: "hang", b: "hung", translation: "colgar" },
  { a: "have", b: "had", translation: "tener" },
  { a: "hear", b: "heard", translation: "oír" },
  { a: "hide", b: "hid", translation: "esconder" },
  { a: "hit", b: "hit", translation: "golpear" },
  { a: "hold", b: "held", translation: "sostener" },
  { a: "hurt", b: "hurt", translation: "herir" },
  { a: "keep", b: "kept", translation: "guardar" },
  { a: "know", b: "knew", translation: "saber/conocer" },
  { a: "lay", b: "laid", translation: "poner (algo)" },
  { a: "lead", b: "led", translation: "liderar" },
  { a: "leave", b: "left", translation: "dejar / irse" },
  { a: "lend", b: "lent", translation: "prestar" },
  { a: "let", b: "let", translation: "permitir" },
  { a: "lie", b: "lay", translation: "acostarse" },
  { a: "light", b: "lit", translation: "encender" },
  { a: "lose", b: "lost", translation: "perder" },
  { a: "make", b: "made", translation: "hacer" },
  { a: "mean", b: "meant", translation: "significar" },
  { a: "meet", b: "met", translation: "conocer / reunirse" },
  { a: "pay", b: "paid", translation: "pagar" },
  { a: "put", b: "put", translation: "poner" },
  { a: "read", b: "read", translation: "leer" },
  { a: "ride", b: "rode", translation: "montar" },
  { a: "ring", b: "rang", translation: "sonar / llamar" },
  { a: "rise", b: "rose", translation: "elevarse" },
  { a: "run", b: "ran", translation: "correr" },
  { a: "say", b: "said", translation: "decir" },
  { a: "see", b: "saw", translation: "ver" },
  { a: "sell", b: "sold", translation: "vender" },
  { a: "send", b: "sent", translation: "enviar" },
  { a: "set", b: "set", translation: "establecer" },
  { a: "shake", b: "shook", translation: "sacudir" },
  { a: "shine", b: "shone", translation: "brillar" },
  { a: "shoot", b: "shot", translation: "disparar" },
  { a: "show", b: "showed", translation: "mostrar" },
  { a: "shut", b: "shut", translation: "cerrar" },
  { a: "sing", b: "sang", translation: "cantar" },
  { a: "sit", b: "sat", translation: "sentarse" },
  { a: "sleep", b: "slept", translation: "dormir" },
  { a: "speak", b: "spoke", translation: "hablar" },
  { a: "spend", b: "spent", translation: "gastar / pasar tiempo" },
  { a: "stand", b: "stood", translation: "estar de pie" },
  { a: "steal", b: "stole", translation: "robar" },
  { a: "swim", b: "swam", translation: "nadar" },
  { a: "take", b: "took", translation: "tomar" },
  { a: "teach", b: "taught", translation: "enseñar" },
  { a: "tell", b: "told", translation: "contar / decir" },
  { a: "think", b: "thought", translation: "pensar" },
  { a: "throw", b: "threw", translation: "lanzar" },
  { a: "understand", b: "understood", translation: "entender" },
  { a: "wake", b: "woke", translation: "despertar" },
  { a: "wear", b: "wore", translation: "llevar puesto" },
  { a: "win", b: "won", translation: "ganar" },
  { a: "write", b: "wrote", translation: "escribir" }
],

pastParticiple: [
  { a: "be", b: "been", translation: "ser/estar" },
  { a: "beat", b: "beaten", translation: "golpear" },
  { a: "become", b: "become", translation: "convertirse en" },
  { a: "begin", b: "begun", translation: "empezar" },
  { a: "bend", b: "bent", translation: "doblar" },
  { a: "bet", b: "bet", translation: "apostar" },
  { a: "bite", b: "bitten", translation: "morder" },
  { a: "blow", b: "blown", translation: "soplar" },
  { a: "break", b: "broken", translation: "romper" },
  { a: "bring", b: "brought", translation: "traer" },
  { a: "build", b: "built", translation: "construir" },
  { a: "burn", b: "burned/burnt", translation: "quemar" },
  { a: "buy", b: "bought", translation: "comprar" },
  { a: "catch", b: "caught", translation: "atrapar" },
  { a: "choose", b: "chosen", translation: "elegir" },
  { a: "come", b: "come", translation: "venir" },
  { a: "cost", b: "cost", translation: "costar" },
  { a: "cut", b: "cut", translation: "cortar" },
  { a: "do", b: "done", translation: "hacer" },
  { a: "draw", b: "drawn", translation: "dibujar" },
  { a: "dream", b: "dreamed/dreamt", translation: "soñar" },
  { a: "drink", b: "drunk", translation: "beber" },
  { a: "drive", b: "driven", translation: "conducir" },
  { a: "eat", b: "eaten", translation: "comer" },
  { a: "fall", b: "fallen", translation: "caer" },
  { a: "feed", b: "fed", translation: "alimentar" },
  { a: "feel", b: "felt", translation: "sentir" },
  { a: "fight", b: "fought", translation: "pelear" },
  { a: "find", b: "found", translation: "encontrar" },
  { a: "fly", b: "flown", translation: "volar" },
  { a: "forget", b: "forgotten", translation: "olvidar" },
  { a: "forgive", b: "forgiven", translation: "perdonar" },
  { a: "freeze", b: "frozen", translation: "congelar" },
  { a: "get", b: "got/gotten", translation: "obtener" },
  { a: "give", b: "given", translation: "dar" },
  { a: "go", b: "gone", translation: "ir" },
  { a: "grow", b: "grown", translation: "crecer" },
  { a: "hang", b: "hung", translation: "colgar" },
  { a: "have", b: "had", translation: "tener" },
  { a: "hear", b: "heard", translation: "oír" },
  { a: "hide", b: "hidden", translation: "esconder" },
  { a: "hit", b: "hit", translation: "golpear" },
  { a: "hold", b: "held", translation: "sostener" },
  { a: "hurt", b: "hurt", translation: "herir" },
  { a: "keep", b: "kept", translation: "guardar" },
  { a: "know", b: "known", translation: "saber/conocer" },
  { a: "lay", b: "laid", translation: "poner (algo)" },
  { a: "lead", b: "led", translation: "liderar" },
  { a: "leave", b: "left", translation: "dejar / irse" },
  { a: "lend", b: "lent", translation: "prestar" },
  { a: "let", b: "let", translation: "permitir" },
  { a: "lie", b: "lain", translation: "acostarse" },
  { a: "light", b: "lit", translation: "encender" },
  { a: "lose", b: "lost", translation: "perder" },
  { a: "make", b: "made", translation: "hacer" },
  { a: "mean", b: "meant", translation: "significar" },
  { a: "meet", b: "met", translation: "conocer / reunirse" },
  { a: "pay", b: "paid", translation: "pagar" },
  { a: "put", b: "put", translation: "poner" },
  { a: "read", b: "read", translation: "leer" },
  { a: "ride", b: "ridden", translation: "montar" },
  { a: "ring", b: "rung", translation: "sonar / llamar" },
  { a: "rise", b: "risen", translation: "elevarse" },
  { a: "run", b: "run", translation: "correr" },
  { a: "say", b: "said", translation: "decir" },
  { a: "see", b: "seen", translation: "ver" },
  { a: "sell", b: "sold", translation: "vender" },
  { a: "send", b: "sent", translation: "enviar" },
  { a: "set", b: "set", translation: "establecer" },
  { a: "shake", b: "shaken", translation: "sacudir" },
  { a: "shine", b: "shone", translation: "brillar" },
  { a: "shoot", b: "shot", translation: "disparar" },
  { a: "show", b: "shown", translation: "mostrar" },
  { a: "shut", b: "shut", translation: "cerrar" },
  { a: "sing", b: "sung", translation: "cantar" },
  { a: "sit", b: "sat", translation: "sentarse" },
  { a: "sleep", b: "slept", translation: "dormir" },
  { a: "speak", b: "spoken", translation: "hablar" },
  { a: "spend", b: "spent", translation: "gastar / pasar tiempo" },
  { a: "stand", b: "stood", translation: "estar de pie" },
  { a: "steal", b: "stolen", translation: "robar" },
  { a: "swim", b: "swum", translation: "nadar" },
  { a: "take", b: "taken", translation: "tomar" },
  { a: "teach", b: "taught", translation: "enseñar" },
  { a: "tell", b: "told", translation: "contar / decir" },
  { a: "think", b: "thought", translation: "pensar" },
  { a: "throw", b: "thrown", translation: "lanzar" },
  { a: "understand", b: "understood", translation: "entender" },
  { a: "wake", b: "woken", translation: "despertar" },
  { a: "wear", b: "worn", translation: "llevar puesto" },
  { a: "win", b: "won", translation: "ganar" },
  { a: "write", b: "written", translation: "escribir" }
],

phrasalVerbs : [
  { a: "ask out", b: "invitar a salir" },
  { a: "break down", b: "averiarse / descomponerse" },
  { a: "break up", b: "romper una relación" },
  { a: "break out", b: "meterse a la fuerza / escaparse" },
  { a: "bring down", b: "ponerse triste / bajar algo" },
  { a: "call back", b: "devolver la llamada" },
  { a: "call up", b: "llamar por teléfono" },
  { a: "call off", b: "cancelar" },
  { a: "calm down", b: "calmarse" },
  { a: "carry out", b: "llevar a cabo" },
  { a: "carry on", b: "seguir adelante, continuar" },
  { a: "come back", b: "regresar" },
  { a: "cheer up", b: "animar" },
  { a: "check out", b: "salir de hotel / revisar" },
  { a: "check in", b: "entrar al hotel" },
  { a: "clean up", b: "limpiar, ordenar" },
  { a: "cross out", b: "tachar" },
  { a: "cut out", b: "dejar de hacer algo" },
  { a: "do over", b: "repetir" },
  { a: "drop out", b: "abandonar (escuela, curso)" },
  { a: "find out", b: "descubrir, averiguar" },
  { a: "figure out", b: "entender, descifrar, resolver" },
  { a: "get along (with)", b: "llevarse bien (con)" },
  { a: "get back (from)", b: "regresar (de)" },
  { a: "get in / into", b: "entrar, subir (a un carro)" },
  { a: "get off", b: "bajar de (bus, tren)" },
  { a: "get on", b: "subir a (bus, tren)" },
  { a: "get out (of)", b: "salir de, evitar" },
  { a: "get up", b: "levantarse" },
  { a: "give back", b: "devolver" },
  { a: "give up", b: "rendirse, dejar de intentar" },
  { a: "go on", b: "continuar" },
  { a: "go after", b: "ir detrás de algo / perseguir" },
  { a: "grow up", b: "crecer" },
  { a: "grow old", b: "envejecer" },
  { a: "hang up", b: "colgar (teléfono)" },
  { a: "hold on", b: "esperar" },
  { a: "have on", b: "llevar puesto" },
  { a: "keep out (of)", b: "no entrar" },
  { a: "keep on", b: "continuar" },
  { a: "kick out (of)", b: "expulsar" },
  { a: "look up", b: "buscar información" },
  { a: "look for", b: "buscar" },
  { a: "look after", b: "cuidar" },
  { a: "look forward to", b: "esperar con ansias" },
  { a: "make up", b: "inventar, reconciliarse, maquillarse" },
  { a: "name after", b: "poner el nombre de alguien" },
  { a: "pass away", b: "fallecer" },
  { a: "pick out", b: "escoger" },
  { a: "pick up", b: "recoger, levantar" },
  { a: "point out", b: "señalar" },
  { a: "put on", b: "ponerse ropa" },
  { a: "put off", b: "posponer" },
  { a: "run out (of)", b: "quedarse sin" },
  { a: "show up", b: "aparecer" },
  { a: "shut off", b: "apagar / cerrar" },
  { a: "take off", b: "despegar / quitarse ropa" },
  { a: "take out", b: "sacar / invitar a salir" },
  { a: "think over", b: "considerar bien" },
  { a: "throw away", b: "botar" },
  { a: "throw up", b: "vomitar" },
  { a: "try on", b: "probarse ropa" },
  { a: "turn down", b: "bajar volumen / rechazar" },
  { a: "turn off", b: "apagar" },
  { a: "turn on", b: "encender" },
  { a: "turn out", b: "resultar" },
  { a: "turn up", b: "subir volumen / aparecer" },
  { a: "sit down", b: "sentarse" },
  { a: "stand up", b: "ponerse de pie" },
  { a: "set up", b: "montar / establecer" },
  { a: "stop trying", b: "dejar de intentar" },
  { a: "wake up", b: "despertarse" },
  { a: "write down", b: "anotar" }
]
};